### PR TITLE
Creates a React app

### PR DESCRIPTION
**Pull request by ChrisAntaki**
Creates a "Hello World" React app using the [`create-react-app`](https://github.com/facebook/create-react-app) tool 👋

### CODE REVIEW

**Comment by danielschwartz** [comment]
@ChrisAntaki I haven't used CRA in a while. Does this initial setup still let us turn on Typescript compilation in the future if we want it?

**Comment by ChrisAntaki** [comment]
Not sure, I'll just run it again with a `typescript` template

**Review by danielschwartz — APPROVED** [review]
:shipit:

**Comment by ChrisAntaki** [comment]
Good call on TypeScript! Do you wanna merge it? I don't have write access
image

**Comment by danielschwartz** [comment]
Womp womp sorry about that. Will merge and give you write access

**Comment by ChrisAntaki** [comment]
Thank you x2!

**Pull request merged**
